export const MAX_AGENT_EVENT_TEXT_BYTES = 16 * 1_024;
export const MAX_AGENT_EVENTS_PER_TURN = 1_024;
export const MAX_SUBAGENT_THREADS_PER_TURN = 32;
export const MAX_AGENT_EVENT_BYTES_PER_TURN = 2 * 1_024 * 1_024;
export const MAX_AGENT_TOOL_SUMMARY_BYTES = 512;
export const MAX_AGENT_TOOL_ID_BYTES = 256;
export const MAX_AGENT_TOOL_NAME_BYTES = 256;
export const MAX_AGENT_TOOL_DESCRIPTION_BYTES = 200;
