export type {
  TestCase as PhpTestCase,
  TestCaseNavigationTarget as PhpTestCaseNavigationTarget,
  TestGateway as PhpTestGateway,
  TestRunOk as PhpTestRunOk,
  TestRunResponse as PhpTestRunResponse,
  TestStatus as PhpTestStatus,
  TestSuite as PhpTestSuite,
  TestTotals as PhpTestTotals,
} from "./testResults";
export {
  isValidTestFilter as isValidPhpTestFilter,
  sortTestCasesFailedFirst as sortPhpTestCasesFailedFirst,
  testCaseCanNavigate as phpTestCaseCanNavigate,
  testCaseCanRun as phpTestCaseCanRun,
  testCaseNavigationTarget as phpTestCaseNavigationTarget,
  testStatusRank as phpTestStatusRank,
  testSuiteStatus as phpTestSuiteStatus,
  testTotalsSummary as phpTestTotalsSummary,
} from "./testResults";
