export type BorderRuleEntry = {
  readonly sheet: string;
  readonly selector: string;
};

export const SEPARATOR_INSET_CONSUMERS: readonly BorderRuleEntry[] = [
  { sheet: "components/settings/settings.css", selector: ".settings-row + .settings-row" },
  {
    sheet: "components/settings/settings.css",
    selector: ".settings-provider + .settings-provider",
  },
];

export const LEGACY_BORDER_RATCHET: readonly BorderRuleEntry[] = [
  { sheet: "App.css", selector: "::-webkit-scrollbar-thumb" },
  { sheet: "App.css", selector: ".breakpoint-editor-dialog input" },
  { sheet: "App.css", selector: ".breakpoint-editor-dialog input:focus" },
  { sheet: "App.css", selector: ".breakpoint-editor-popover" },
  { sheet: "App.css", selector: ".call-hierarchy" },
  { sheet: "App.css", selector: ".call-hierarchy-header" },
  { sheet: "App.css", selector: ".call-hierarchy-section + .call-hierarchy-section" },
  { sheet: "App.css", selector: ".editor-change-popover" },
  { sheet: "App.css", selector: ".editor-change-popover-actions" },
  { sheet: "App.css", selector: ".editor-change-popover-header" },
  {
    sheet: "App.css",
    selector: ".editor-change-popover-icon-button, .editor-change-popover-action",
  },
  {
    sheet: "App.css",
    selector: ".editor-change-popover-icon-button:hover, .editor-change-popover-action:hover",
  },
  { sheet: "App.css", selector: ".editor-change-popover-kind::before" },
  { sheet: "App.css", selector: ".editor-change-popover-section-label" },
  { sheet: "App.css", selector: ".file-history-commits" },
  { sheet: "App.css", selector: ".file-history-header" },
  { sheet: "App.css", selector: ".file-history-header button" },
  { sheet: "App.css", selector: ".file-history-header button:hover" },
  { sheet: "App.css", selector: ".file-history-panel" },
  { sheet: "App.css", selector: ".file-structure" },
  { sheet: "App.css", selector: ".file-structure-option" },
  { sheet: "App.css", selector: ".git-branch-actions-bar" },
  { sheet: "App.css", selector: ".git-branch-filter" },
  { sheet: "App.css", selector: ".git-branch-force-delete" },
  { sheet: "App.css", selector: ".git-branch-new-button" },
  { sheet: "App.css", selector: ".git-branch-new-button:hover:not(:disabled)" },
  { sheet: "App.css", selector: ".git-branch-rename-form input" },
  { sheet: "App.css", selector: ".git-commit-footer" },
  { sheet: "App.css", selector: ".git-commit-header" },
  { sheet: "App.css", selector: ".git-commit-history-list" },
  { sheet: "App.css", selector: ".git-commit-message" },
  { sheet: "App.css", selector: ".git-commit-message:focus" },
  { sheet: "App.css", selector: ".git-conventional-commit-hints" },
  { sheet: "App.css", selector: ".git-diff-header" },
  { sheet: "App.css", selector: ".git-diff-header button" },
  { sheet: "App.css", selector: ".git-diff-header button:hover:not(:disabled)" },
  { sheet: "App.css", selector: ".git-diff-hunk" },
  { sheet: "App.css", selector: ".git-diff-hunk button" },
  { sheet: "App.css", selector: ".git-diff-pane-labels" },
  { sheet: "App.css", selector: ".git-diff-pane-labels span + span" },
  {
    sheet: "App.css",
    selector: ".git-history-branches, .git-history-commits, .git-history-details",
  },
  { sheet: "App.css", selector: ".git-history-commit-meta-panel" },
  { sheet: "App.css", selector: ".git-history-commit-row--merge" },
  { sheet: "App.css", selector: ".git-history-filter" },
  { sheet: "App.css", selector: ".git-history-group-toggle" },
  { sheet: "App.css", selector: ".git-history-labels span" },
  { sheet: "App.css", selector: ".git-history-refresh" },
  { sheet: "App.css", selector: ".git-history-refresh:hover" },
  { sheet: "App.css", selector: ".git-history-section-header" },
  { sheet: "App.css", selector: ".git-remote-branches-section" },
  { sheet: "App.css", selector: ".git-themed-checkbox-box" },
  { sheet: "App.css", selector: ".git-themed-checkbox:hover .git-themed-checkbox-box" },
  { sheet: "App.css", selector: ".git-themed-checkbox.checked .git-themed-checkbox-box" },
  { sheet: "App.css", selector: ".image-viewer-footer" },
  { sheet: "App.css", selector: ".implementation-chooser" },
  { sheet: "App.css", selector: ".implementation-chooser-header" },
  { sheet: "App.css", selector: ".index-health-actions button" },
  { sheet: "App.css", selector: ".index-health-actions button:hover:not(:disabled)" },
  { sheet: "App.css", selector: ".local-history-diff-toolbar" },
  { sheet: "App.css", selector: ".local-history-revert" },
  { sheet: "App.css", selector: ".markdown-preview-content blockquote" },
  { sheet: "App.css", selector: ".markdown-preview-content h1, .markdown-preview-content h2" },
  { sheet: "App.css", selector: ".markdown-preview-content th, .markdown-preview-content td" },
  { sheet: "App.css", selector: ".monaco-editor .action-widget, .action-widget" },
  { sheet: "App.css", selector: ".monaco-editor .bookmark-gutter-glyph::before" },
  { sheet: "App.css", selector: ".monaco-editor .breakpoint-glyph-unverified::before" },
  { sheet: "App.css", selector: ".monaco-editor .breakpoint-glyph-verified::before" },
  { sheet: "App.css", selector: ".monaco-editor .editor-change-glyph-added::before" },
  { sheet: "App.css", selector: ".monaco-editor .editor-change-glyph-deleted::before" },
  { sheet: "App.css", selector: ".monaco-editor .editor-change-glyph-modified::before" },
  { sheet: "App.css", selector: ".monaco-editor .editor-change-line-added" },
  {
    sheet: "App.css",
    selector:
      ".monaco-editor .editor-change-line-added, .monaco-editor .editor-change-line-modified, .monaco-editor .editor-change-line-deleted",
  },
  { sheet: "App.css", selector: ".monaco-editor .editor-change-line-deleted" },
  { sheet: "App.css", selector: ".monaco-editor .editor-change-line-modified" },
  { sheet: "App.css", selector: ".monaco-editor .git-blame-annotation" },
  { sheet: "App.css", selector: ".monaco-editor .implementation-gutter-glyph::after" },
  { sheet: "App.css", selector: ".monaco-editor .implementation-gutter-glyph::before" },
  { sheet: "App.css", selector: ".monaco-editor .implementation-gutter-glyph:hover::before" },
  { sheet: "App.css", selector: ".monaco-editor .monaco-hover, .monaco-hover" },
  { sheet: "App.css", selector: ".monaco-editor .suggest-widget .suggest-details" },
  { sheet: "App.css", selector: ".monaco-editor .suggest-widget, .monaco-editor.rename-box" },
  { sheet: "App.css", selector: ".monaco-editor .test-run-gutter-glyph::before" },
  { sheet: "App.css", selector: ".monaco-editor .test-run-gutter-glyph:hover::before" },
  { sheet: "App.css", selector: ".project-tab" },
  { sheet: "App.css", selector: ".project-tab + .project-tab" },
  { sheet: "App.css", selector: ".project-tab.active" },
  { sheet: "App.css", selector: ".project-tabs" },
  { sheet: "App.css", selector: ".references-panel" },
  { sheet: "App.css", selector: ".references-panel-group + .references-panel-group" },
  { sheet: "App.css", selector: ".references-panel-header" },
  { sheet: "App.css", selector: ".references-panel-pagination" },
  { sheet: "App.css", selector: ".references-panel-pagination button" },
  { sheet: "App.css", selector: ".runtime-observability-actions button" },
  { sheet: "App.css", selector: ".runtime-observability-actions button:hover:not(:disabled)" },
  { sheet: "App.css", selector: ".runtime-observability-copy-bundle" },
  { sheet: "App.css", selector: ".runtime-observability-copy-bundle:hover" },
  { sheet: "App.css", selector: ".runtime-observability-latency" },
  {
    sheet: "App.css",
    selector: ".runtime-observability-latency-table th, .runtime-observability-latency-table td",
  },
  {
    sheet: "App.css",
    selector: ".runtime-observability-requests-table th, .runtime-observability-requests-table td",
  },
  { sheet: "App.css", selector: ".runtime-observability-row" },
  { sheet: "App.css", selector: ".runtime-observability-stderr-tail" },
  { sheet: "App.css", selector: ".sidebar" },
  { sheet: "App.css", selector: ".sidebar-header" },
  { sheet: "App.css", selector: ".sidebar-header button" },
  { sheet: "App.css", selector: ".sidebar-header button:hover:not(:disabled)" },
  { sheet: "App.css", selector: ".sidebar-tab" },
  { sheet: "App.css", selector: ".sidebar-tab.active" },
  { sheet: "App.css", selector: ".smart-mode-switch" },
  { sheet: "App.css", selector: ".switch-thumb" },
  { sheet: "App.css", selector: '.symbol-icon[data-static="true"]' },
  { sheet: "App.css", selector: ".todo-panel" },
  { sheet: "App.css", selector: ".todo-panel-action" },
  { sheet: "App.css", selector: ".todo-panel-action:hover:not(:disabled)" },
  { sheet: "App.css", selector: ".todo-panel-group + .todo-panel-group" },
  { sheet: "App.css", selector: ".todo-panel-header" },
  { sheet: "App.css", selector: ".toolbar-progress" },
  { sheet: "App.css", selector: ".toolbar-progress:hover" },
  { sheet: "App.css", selector: ".toolbar-progress.problem" },
  { sheet: "App.css", selector: ".toolbar-progress.scanning" },
  { sheet: "App.css", selector: ".workbench-toolbar" },
  {
    sheet: "components/DirtyCloseDecisionDialogHost.css",
    selector: ".dirty-close-decision-content .dirty-close-decision-save",
  },
  {
    sheet: "components/DirtyCloseDecisionDialogHost.css",
    selector: ".dirty-close-decision-content button",
  },
  {
    sheet: "components/DirtyCloseDecisionDialogHost.css",
    selector: ".dirty-close-decision-content ul",
  },
  { sheet: "components/ExternalFileConflict.css", selector: ".external-file-compare-header" },
  { sheet: "components/ExternalFileConflict.css", selector: ".external-file-compare-labels" },
  {
    sheet: "components/ExternalFileConflict.css",
    selector: ".external-file-compare-labels span + span",
  },
  {
    sheet: "components/ExternalFileConflict.css",
    selector: ".external-file-compare-labels-inline span + span",
  },
  {
    sheet: "components/ExternalFileConflict.css",
    selector: ".external-file-conflict-action-primary",
  },
  {
    sheet: "components/ExternalFileConflict.css",
    selector: ".external-file-conflict-action, .external-file-compare-close",
  },
  {
    sheet: "components/PhpChangeSignatureDialog.css",
    selector: ".php-change-signature-dialog > footer",
  },
  {
    sheet: "components/PhpChangeSignatureDialog.css",
    selector: ".php-change-signature-dialog > footer .php-change-signature-apply",
  },
  {
    sheet: "components/PhpChangeSignatureDialog.css",
    selector: ".php-change-signature-dialog > header",
  },
  {
    sheet: "components/PhpChangeSignatureDialog.css",
    selector: ".php-change-signature-dialog > header, .php-change-signature-dialog > footer",
  },
  {
    sheet: "components/PhpChangeSignatureDialog.css",
    selector: ".php-change-signature-dialog button",
  },
  { sheet: "components/PhpChangeSignatureDialog.css", selector: ".php-change-signature-error" },
  { sheet: "components/PhpChangeSignatureDialog.css", selector: ".php-change-signature-preview" },
  {
    sheet: "components/PhpChangeSignatureDialog.css",
    selector: ".php-change-signature-table-wrap input",
  },
  {
    sheet: "components/PhpChangeSignatureDialog.css",
    selector: ".php-change-signature-table-wrap td",
  },
];

export const PENDING_SCOPE: readonly BorderRuleEntry[] = [];
