import type * as Monaco from "monaco-editor";

export function registerMonacoAppThemes(monaco: typeof Monaco): void {
  const calmDarkWidget = {
    "editorSuggestWidget.background": "#1b1e24",
    "editorSuggestWidget.border": "#2c303a",
    "editorSuggestWidget.foreground": "#c2c8d2",
    "editorSuggestWidget.selectedBackground": "#23303a",
    "editorSuggestWidget.selectedForeground": "#eef1f5",
    "editorSuggestWidget.highlightForeground": "#8aa9c9",
    "editorSuggestWidget.focusHighlightForeground": "#8aa9c9",
    "editorWidget.background": "#1b1e24",
    "editorWidget.border": "#2c303a",
    "editorHoverWidget.background": "#1b1e24",
    "editorHoverWidget.border": "#2c303a",
    "input.background": "#16181d",
    "input.border": "#2c303a",
    focusBorder: "#8aa9c9",
  };

  monaco.editor.defineTheme("mockor-calm-dark", {
    base: "vs-dark",
    colors: {
      "activityBar.background": "#16181d",
      "editor.background": "#16181d",
      "editor.foreground": "#c2c8d2",
      "editor.lineHighlightBackground": "#1d2026",
      "editor.selectionBackground": "#28323d",
      "editorCursor.foreground": "#8aa9c9",
      "editorGutter.background": "#16181d",
      "editorLineNumber.activeForeground": "#c2c8d2",
      "editorLineNumber.foreground": "#5e6573",
      "editorWhitespace.foreground": "#2c303a",
      ...calmDarkWidget,
    },
    inherit: true,
    rules: [],
  });

  monaco.editor.defineTheme("mockor-calm-light", {
    base: "vs",
    colors: {
      "activityBar.background": "#f5f7f9",
      "editor.background": "#f5f7f9",
      "editor.foreground": "#3a4654",
      "editor.lineHighlightBackground": "#eef1f4",
      "editor.selectionBackground": "#d3e1e7",
      "editorCursor.foreground": "#3d7c8a",
      "editorGutter.background": "#f5f7f9",
      "editorLineNumber.activeForeground": "#3a4654",
      "editorLineNumber.foreground": "#9aa7b6",
      "editorWhitespace.foreground": "#cfd6de",
      "editorSuggestWidget.background": "#ffffff",
      "editorSuggestWidget.border": "#e2e7ec",
      "editorSuggestWidget.foreground": "#3a4654",
      "editorSuggestWidget.selectedBackground": "#dbe8ed",
      "editorSuggestWidget.selectedForeground": "#1b2733",
      "editorSuggestWidget.highlightForeground": "#3d7c8a",
      "editorSuggestWidget.focusHighlightForeground": "#3d7c8a",
      "editorWidget.background": "#ffffff",
      "editorWidget.border": "#e2e7ec",
      "editorHoverWidget.background": "#ffffff",
      "editorHoverWidget.border": "#e2e7ec",
      "input.background": "#ffffff",
      "input.border": "#cfd6de",
      focusBorder: "#3d7c8a",
    },
    inherit: true,
    rules: [],
  });

  monaco.editor.defineTheme("mockor-ayu-mirage", {
    base: "vs-dark",
    colors: {
      "activityBar.background": "#1f2430",
      "editor.background": "#1f2430",
      "editor.foreground": "#cbccc6",
      "editor.lineHighlightBackground": "#242b38",
      "editor.selectionBackground": "#33415e",
      "editorCursor.foreground": "#ffcc66",
      "editorGutter.background": "#1f2430",
      "editorLineNumber.activeForeground": "#ffd580",
      "editorLineNumber.foreground": "#707a8c",
      "editorWhitespace.foreground": "#3b4557",
      "editorSuggestWidget.background": "#242b38",
      "editorSuggestWidget.border": "#3a4453",
      "editorSuggestWidget.foreground": "#c4c6c1",
      "editorSuggestWidget.selectedBackground": "#2f3a4f",
      "editorSuggestWidget.selectedForeground": "#fff3d4",
      "editorSuggestWidget.highlightForeground": "#eec07a",
      "editorSuggestWidget.focusHighlightForeground": "#eec07a",
      "editorWidget.background": "#242b38",
      "editorWidget.border": "#3a4453",
      "editorHoverWidget.background": "#242b38",
      "editorHoverWidget.border": "#3a4453",
      "input.background": "#1f2430",
      "input.border": "#3a4453",
      focusBorder: "#eec07a",
    },
    inherit: true,
    rules: [
      { foreground: "ffcc66", token: "keyword" },
      { foreground: "ffd580", token: "string" },
      { foreground: "bae67e", token: "number" },
      { foreground: "73d0ff", token: "type" },
      { foreground: "95e6cb", token: "function" },
      { foreground: "5ccfe6", token: "variable" },
      { foreground: "707a8c", fontStyle: "italic", token: "comment" },
    ],
  });

  monaco.editor.defineTheme("mockor-material-deep-ocean", {
    base: "vs-dark",
    colors: {
      "activityBar.background": "#0f111a",
      "editor.background": "#0f111a",
      "editor.foreground": "#d8dee9",
      "editor.lineHighlightBackground": "#161b2a",
      "editor.selectionBackground": "#26345c",
      "editorCursor.foreground": "#84ffff",
      "editorGutter.background": "#0f111a",
      "editorLineNumber.activeForeground": "#c792ea",
      "editorLineNumber.foreground": "#54617d",
      "editorWhitespace.foreground": "#2a3148",
      "editorSuggestWidget.background": "#161a26",
      "editorSuggestWidget.border": "#2f3754",
      "editorSuggestWidget.foreground": "#c6cdda",
      "editorSuggestWidget.selectedBackground": "#20305a",
      "editorSuggestWidget.selectedForeground": "#ffffff",
      "editorSuggestWidget.highlightForeground": "#7fd6d6",
      "editorSuggestWidget.focusHighlightForeground": "#7fd6d6",
      "editorWidget.background": "#161a26",
      "editorWidget.border": "#2f3754",
      "editorHoverWidget.background": "#161a26",
      "editorHoverWidget.border": "#2f3754",
      "input.background": "#0f111a",
      "input.border": "#2f3754",
      focusBorder: "#7fd6d6",
    },
    inherit: true,
    rules: [
      { foreground: "c792ea", token: "keyword" },
      { foreground: "c3e88d", token: "string" },
      { foreground: "f78c6c", token: "number" },
      { foreground: "ffcb6b", token: "type" },
      { foreground: "82aaff", token: "function" },
      { foreground: "89ddff", token: "variable" },
      { foreground: "54617d", fontStyle: "italic", token: "comment" },
    ],
  });
}
