export const DEBUG_LIST_VIRTUALIZATION_THRESHOLD = 50;
export const DEBUG_LIST_VIEWPORT_HEIGHT = 240;
export const CALL_STACK_ROW_HEIGHT = 25;
export const BREAKPOINT_ROW_HEIGHT = 36;
export const BREAKPOINT_GROUP_ROW_HEIGHT = 28;
