import type { SettingsRowAvailability, SettingsSectionId } from "./settingsRegistry";

interface SettingsRowRecord {
  readonly id: string;
  readonly section: SettingsSectionId;
  readonly title: string;
  readonly description: string | null;
  readonly keywords: ReadonlyArray<string>;
  readonly availability: SettingsRowAvailability;
}

function row<Id extends string>(
  id: Id,
  section: SettingsSectionId,
  title: string,
  description: string | null,
  keywords: ReadonlyArray<string>,
  availability: SettingsRowAvailability = "always",
): SettingsRowRecord & { readonly id: Id } {
  return { id, section, title, description, keywords, availability };
}

export const SETTINGS_ROW_TABLE = [
  row(
    "general.appUpdates",
    "general",
    "Application updates",
    "Check for a new Codevo release, download it, and install it on restart.",
    ["update", "release", "version", "download", "install"],
  ),
  row(
    "general.workspaceRoot",
    "general",
    "Workspace root",
    "The project directory this window edits.",
    ["project", "root", "folder", "workspace"],
  ),
  row(
    "general.intelligenceMode",
    "general",
    "Mode",
    "Editor Mode, Smart Index, or full IDE Mode for this workspace.",
    ["intelligence", "smart", "ide", "editor mode"],
    "workspace",
  ),
  row(
    "general.trustedWorkspace",
    "general",
    "Trusted workspace",
    "Trusted projects may run workspace binaries, tasks, and language servers.",
    ["trust", "security", "execute"],
    "workspace",
  ),
  row(
    "general.revealActiveFileInTree",
    "general",
    "Reveal active file in tree",
    "Select the open file in the project tree while you switch editors.",
    ["reveal", "tree", "explorer", "follow"],
    "workspace",
  ),
  row(
    "general.backgroundRuntimePolicy",
    "general",
    "Background IDE engines",
    "Keep, suspend, or stop language engines for projects in background windows.",
    ["runtime", "engine", "background", "suspend", "memory"],
  ),
  row(
    "general.terminalShellIntegration",
    "general",
    "Terminal shell integration",
    "Track command boundaries and exit codes in the integrated terminal.",
    ["terminal", "shell", "integration"],
  ),
  row(
    "general.autoSave",
    "general",
    "Auto save",
    "Write editor changes to disk without an explicit save.",
    ["auto save", "persist"],
    "workspace",
  ),
  row(
    "general.formatOnSave",
    "general",
    "Format on save",
    "Run the language formatter before the file is written.",
    ["format", "save", "prettier"],
    "workspace",
  ),
  row(
    "general.formatOnPaste",
    "general",
    "Format on paste",
    "Reformat pasted text with the language formatter.",
    ["format", "paste"],
    "workspace",
  ),
  row(
    "general.optimizeImportsOnSave",
    "general",
    "Optimize imports on save",
    "Drop unused imports and sort the remaining ones before writing.",
    ["imports", "optimize", "save"],
    "workspace",
  ),
  row(
    "general.defaultTabSize",
    "general",
    "Default tab size",
    "Indent width used when a file has no detected indentation.",
    ["tab", "indent", "width"],
    "workspace",
  ),
  row(
    "general.defaultInsertSpaces",
    "general",
    "Insert spaces by default",
    "Indent with spaces instead of tab characters.",
    ["indent", "spaces", "tabs"],
    "workspace",
  ),
  row(
    "general.statusBar",
    "general",
    "Status bar items",
    "Choose which readouts the status bar shows.",
    ["status bar", "visibility", "items"],
    "workspace",
  ),
  row("appearance.theme", "appearance", "Theme", "Colour theme for the whole window.", [
    "theme",
    "colour",
    "color",
    "dark",
    "light",
  ]),
  row(
    "appearance.agentAppearance",
    "appearance",
    "Agent appearance",
    "Visual variant used by the agent workbench.",
    ["agent", "variant", "graphite", "paper", "studio"],
  ),
  row(
    "appearance.agentThreadFontSize",
    "appearance",
    "Agent thread text size",
    "Thread body text size in pixels. The whole agent workbench type scale follows it.",
    ["agent", "thread", "text size", "font size", "scale", "zoom"],
  ),
  row(
    "appearance.editorFontFamily",
    "appearance",
    "Editor font family",
    "Monospace family used by the editor and terminal.",
    ["font", "family", "monospace"],
  ),
  row(
    "appearance.editorFontSize",
    "appearance",
    "Editor font size",
    "Editor text size in pixels.",
    ["font", "size", "zoom"],
  ),
  row(
    "appearance.editorFontLigatures",
    "appearance",
    "Font ligatures",
    "Render programming ligatures when the font provides them.",
    ["font", "ligatures"],
  ),
  row("appearance.minimap", "appearance", "Minimap", "Show the code overview beside the editor.", [
    "minimap",
    "overview",
  ]),
  row("appearance.wordWrap", "appearance", "Word wrap", "Wrap long lines at the viewport width.", [
    "wrap",
    "word wrap",
    "lines",
  ]),
  row(
    "agents.healthCheckInterval",
    "agents",
    "Update check interval",
    "Compare known CLI versions with the latest available releases in the background, without checking sign-in status. Applies to both providers; 0 seconds means manual update checks only.",
    ["agent", "provider", "update", "interval", "refresh"],
  ),
  row(
    "agents.checkCliUpdates",
    "agents",
    "Check CLI updates",
    "Update checks run automatically for enabled providers. Version checks read public metadata only; no prompts are sent.",
    ["agent", "provider", "update", "cli", "version"],
  ),
  row(
    "agents.providerClaudeCode",
    "agents",
    "Claude Code",
    "Executable path, discovery status, and enablement for the Claude Code CLI.",
    ["provider", "claude", "cli", "sign in", "path"],
  ),
  row(
    "agents.providerCodex",
    "agents",
    "Codex",
    "Executable path, discovery status, and enablement for the Codex CLI.",
    ["provider", "codex", "cli", "sign in", "path"],
  ),
  row(
    "agents.defaultProvider",
    "agents",
    "Default provider",
    "Only enabled providers are listed.",
    ["agent", "cli", "default", "provider"],
  ),
  row(
    "agents.favoriteModels",
    "agents",
    "Favorite models",
    "Favorites appear first in the composer picker.",
    ["agent", "model", "favorite", "clear"],
  ),
  row(
    "agents.maxConcurrentTasks",
    "agents",
    "Parallel threads",
    "Shared across all projects. Each provider manages its own subagents and limits.",
    ["agent", "concurrency", "parallel", "threads", "subagents", "projects"],
  ),
  row(
    "agents.isolationPolicy",
    "agents",
    "Workspace isolation policy",
    "Automatic prefers a worktree when the repository is busy, dirty, or has unsaved editors.",
    ["agent", "worktree", "isolation", "in-place"],
    "workspace",
  ),
  row(
    "keymap.bindings",
    "keymap",
    "Keyboard shortcuts",
    "Rebind, reset, or unbind every editor command.",
    ["keymap", "shortcut", "binding", "keyboard", "chord"],
  ),
  row(
    "index.largeFileCharacterLimit",
    "index",
    "Large file character limit",
    "Files above this size fall back to large file mode.",
    ["index", "large file", "characters", "limit"],
    "workspace",
  ),
  row(
    "index.largeFileLineLimit",
    "index",
    "Large file line limit",
    "Files above this line count fall back to large file mode.",
    ["index", "large file", "lines", "limit"],
    "workspace",
  ),
  row(
    "index.extraIgnorePatterns",
    "index",
    "Extra ignores",
    "One glob per line, applied on top of the built-in ignores.",
    ["index", "ignore", "glob", "exclude"],
    "workspace",
  ),
  row(
    "index.builtInIgnores",
    "index",
    "Built-in ignores",
    "Directories the indexer always skips.",
    ["index", "ignore", "node_modules", "vendor"],
  ),
  row(
    "index.javaScriptTypeScriptService",
    "index",
    "JavaScript/TypeScript service",
    "Run the TypeScript language service for this workspace.",
    ["typescript", "javascript", "service", "tsserver"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptVersion",
    "index",
    "TypeScript version",
    "Use the managed TypeScript or the one installed in the workspace.",
    ["typescript", "version", "workspace", "managed"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptValidation",
    "index",
    "JavaScript/TypeScript validation",
    "Report TypeScript diagnostics in the editor and Problems.",
    ["typescript", "validation", "diagnostics"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptAutoImports",
    "index",
    "JavaScript/TypeScript auto imports",
    "Offer auto import completions from the project and its packages.",
    ["typescript", "auto import", "completion"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptImportModuleSpecifier",
    "index",
    "JS/TS import module specifier",
    "Shape of the specifier written by auto imports.",
    ["typescript", "import", "specifier", "relative"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptImportModuleSpecifierEnding",
    "index",
    "JS/TS import module specifier ending",
    "File extension written by auto imports.",
    ["typescript", "import", "extension", "ending"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptQuotePreference",
    "index",
    "JS/TS import quotes",
    "Quote style used by generated imports.",
    ["typescript", "quotes", "single", "double"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptPreferTypeOnlyAutoImports",
    "index",
    "JS/TS prefer type-only auto imports",
    "Write `import type` when only the type is used.",
    ["typescript", "type only", "import"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptAutomaticTypeAcquisition",
    "index",
    "JavaScript/TypeScript automatic type acquisition",
    "Fetch bundled type declarations for untyped dependencies.",
    ["typescript", "types", "acquisition", "ata"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptInlayHints",
    "index",
    "JavaScript/TypeScript inlay hints",
    "Show inferred parameter and type hints inline.",
    ["typescript", "inlay", "hints"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptCodeLens",
    "index",
    "JavaScript/TypeScript CodeLens",
    "Show reference counts above declarations.",
    ["typescript", "codelens", "references"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptReferencesCodeLensOnAllFunctions",
    "index",
    "JS/TS reference CodeLens on all functions",
    "Extend the reference CodeLens to every function declaration.",
    ["typescript", "codelens", "functions"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptCompleteFunctionCalls",
    "index",
    "JS/TS complete function calls",
    "Insert parentheses and argument placeholders on completion.",
    ["typescript", "completion", "arguments"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptOrganizeImportsOnSave",
    "index",
    "JS/TS organize imports on save",
    "Sort and group imports before the file is written.",
    ["typescript", "organize imports", "save"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptRemoveUnusedOnSave",
    "index",
    "JS/TS remove unused on save",
    "Delete unused declarations before the file is written.",
    ["typescript", "unused", "save"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptAddMissingImportsOnSave",
    "index",
    "JS/TS add missing imports on save",
    "Add the imports the file needs before it is written.",
    ["typescript", "missing imports", "save"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptFixAllOnSave",
    "index",
    "JS/TS fix all on save",
    "Apply every safe TypeScript quick fix before the file is written.",
    ["typescript", "fix all", "save"],
    "workspace",
  ),
  row(
    "index.javaScriptTypeScriptServiceActions",
    "index",
    "JavaScript/TypeScript service actions",
    "Restart the language service or open its log.",
    ["typescript", "restart", "log", "service"],
    "workspace",
  ),
  row(
    "index.nodeLaunchConfigurations",
    "index",
    "Node launch configurations",
    "Edit the launch configurations used by the Node debugger.",
    ["node", "launch", "debug", "configuration"],
    "workspace",
  ),
  row(
    "index.eslintPath",
    "index",
    "ESLint path",
    "Executable used for ESLint analysis; empty resolves from the workspace.",
    ["eslint", "path", "lint"],
    "workspace",
  ),
  row(
    "index.eslintAnalyseOnSave",
    "index",
    "ESLint analyse on save",
    "Run ESLint and publish its diagnostics when a file is written.",
    ["eslint", "analyse", "save", "lint"],
    "workspace",
  ),
  row(
    "index.eslintFixOnSave",
    "index",
    "ESLint fix on save",
    "Apply ESLint's safe fixes before the file is written.",
    ["eslint", "fix", "save"],
    "workspace",
  ),
  row(
    "index.prettierFormatOnSave",
    "index",
    "Prettier format on save",
    "Format with the workspace Prettier when a file is written.",
    ["prettier", "format", "save"],
    "workspace",
  ),
  row(
    "index.gitDirectoryMappingsAuto",
    "index",
    "Detect repositories automatically",
    "Discover nested package repositories when the workspace opens.",
    ["git", "repository", "detect", "mapping"],
    "workspace",
  ),
  row(
    "index.gitDirectoryMappings",
    "index",
    "Git directory mappings",
    "Route git operations per directory for a workspace with nested repositories.",
    ["git", "directory", "mapping", "repository", "monorepo"],
    "workspace",
  ),
  row(
    "php.backend",
    "php",
    "PHP backend",
    "Language engine used for PHP intelligence.",
    ["php", "backend", "phpactor", "intelephense"],
    "workspace",
  ),
  row(
    "php.versionOverride",
    "php",
    "PHP language level override",
    "Overrides the level detected from composer.json.",
    ["php", "version", "level", "composer"],
    "workspace",
  ),
  row(
    "php.phpactorPath",
    "php",
    "PHP engine path",
    "Executable used for the managed PHP engine.",
    ["php", "phpactor", "path"],
    "workspace",
  ),
  row(
    "php.intelephensePath",
    "php",
    "Intelephense path",
    "Executable used for Intelephense.",
    ["php", "intelephense", "path"],
    "workspace",
  ),
  row(
    "php.phpstanPath",
    "php",
    "PHPStan path",
    "Executable used for PHPStan analysis.",
    ["php", "phpstan", "path"],
    "workspace",
  ),
  row(
    "php.phpstanAnalyseOnSave",
    "php",
    "PHPStan analyse on save",
    "Run PHPStan and publish its diagnostics when a PHP file is written.",
    ["php", "phpstan", "analyse", "save"],
    "workspace",
  ),
  row(
    "php.inlayHints",
    "php",
    "PHP inlay hints",
    "Show inferred parameter and type hints in PHP files.",
    ["php", "inlay", "hints"],
    "workspace",
  ),
  row(
    "php.composerPhpVersion",
    "php",
    "Composer PHP",
    "PHP level declared by the workspace composer.json.",
    ["php", "composer", "version"],
    "workspace",
  ),
  row(
    "php.effectivePhpLevel",
    "php",
    "Effective PHP level",
    "Level actually used after the override is applied.",
    ["php", "level", "effective"],
    "workspace",
  ),
  row(
    "php.detectedPhpEngine",
    "php",
    "Detected PHP engine",
    "Managed PHP engine discovered for this workspace.",
    ["php", "phpactor", "detected"],
    "workspace",
  ),
  row(
    "php.detectedIntelephense",
    "php",
    "Detected Intelephense",
    "Intelephense executable discovered for this workspace.",
    ["php", "intelephense", "detected"],
    "workspace",
  ),
  row(
    "snippets.userSnippets",
    "snippets",
    "User snippets",
    "Live templates shared across every project, expanded by prefix.",
    ["snippet", "template", "prefix", "expand"],
  ),
] as const;
